create table if not exists app_user (
    user_id bigint generated by default as identity primary key,
    open_id varchar(64) not null,
    nick_name varchar(64) not null,
    avatar_url varchar(255),
    status char(1) not null default '0',
    last_login_time timestamp,
    create_time timestamp,
    update_time timestamp,
    remark varchar(255),
    constraint uk_app_user_open_id unique (open_id)
);
